/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_molo_app_NativeMethod */

#ifndef _Included_com_molo_app_NativeMethod
#define _Included_com_molo_app_NativeMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_molo_app_NativeMethod
 * Method:    doLogin
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_molo_app_NativeMethod_doLogin
  (JNIEnv *, jobject, jstring, jstring,jobject);

/*
 * Class:     com_molo_app_NativeMethod
 * Method:    createChannel
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_molo_app_NativeMethod_createChannel
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_molo_app_NativeMethod
 * Method:    sendData
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_molo_app_NativeMethod_sendData
  (JNIEnv *, jobject, jstring, jstring);        

JNIEXPORT jboolean JNICALL Java_com_molo_app_NativeMethod_quit
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL  JNI_OnLoad(JavaVM *ajvm, void *reserved);    

JNIEXPORT void JNICALL JNI_OnUnload(JavaVM* vm, void* reserved); 

#ifdef __cplusplus
}
#endif
#endif
